fix: building a wheel
this fixes two issues when building a wheel using pyproject-build.
The first issue
```
ERROR Missing dependencies:
  poetry>=0.12
```
can be resolved by requiring poetry-core over poetry>=0.12

The second issue
```
ModuleNotFoundError: No module named 'poetry.masonry'
```
can be resolved by importing the correct module from poetry.core.

see also https://pypi.org/project/poetry-core/